### ISSUE TITLE
Change script syntax to improve readability using yaml

### ISSUE THREAD

**Issue by Bogyie** [gptscript-ai/gptscript#66]
I think, we can improve readability of script when use yaml syntax.

Also, this feature is able to make the parsing process simpler than before.

### Current
```yaml
tools: myfunction
What's the myfunction of 3

----
name: myfunction
tools: sub, mul
description: A function taking an integer as argument and returns an integer
args: number: An integer
tools: myfunction

Do the following in strict order:
1. If ${number} is 0 skip the remaining steps and return 1
2. Calculate the myfunction of (${number} - 1)
3. Return ${number} multiply the result of the previous step

---
name: sub
description: Subtract two numbers
args: left: a number
args: right: a number

#!/bin/bash

echo $((${LEFT} - ${RIGHT}))

---
name: mul
description: Multiply two numbers
args: left: a number
args: right: a number

#!/bin/bash

echo $((${LEFT} * ${RIGHT}))
```

### New format
```yaml
tools: 
  - myfunction
body: >
  What's the myfunction of 3

----
name: myfunction
tools: 
  - sub
  - mul
description: A function taking an integer as argument and returns an integer
args: 
  - number: An integer
tools: 
  - myfunction
body: >
  Do the following in strict order:
  1. If ${number} is 0 skip the remaining steps and return 1
  2. Calculate the myfunction of (${number} - 1)
  3. Return ${number} multiply the result of the previous step

---
name: sub
description: Subtract two numbers
args: 
  - left: a number
  - right: a number
body: >
  #!/bin/bash
  
  echo $((${left} - ${right}))

---
name: mul
description: Multiply two numbers
args: 
  - left: a number
  - right: a number
body: >
  #!/bin/bash
  
  echo $((${left} * ${right}))
```
